apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgB7OtiGLe9jgUuQxYc4C5bMKOudJ95wG/9FU67NLZOwaAbpDfo8v+PRLQ6gLcUOSU7giMlWxetGT0axFDEotUt9f/1F3PueRshXuHH6v2zmz5QqQw+XX83NQ/JyTcG62ROBy8xQ9k3R6nBxExaMFVS9vtYgLqAlSk8nTT9jyhXTRl3IqC9a3ap4B4wP6SfibzfDl53IGcgWvM/O+vOkOdCFIk0F6Tu/AOuLiiLVP1whaBeywbSlZkQDDZyDO08m5048RSsm/X+4FGAvt7q/2Z7XzAmZfB5fyfg2n8sydKbfI9ebL0gHWoGp525Clm0qJ0FLOc4ZMIq8fnaU3p6gU2nBVefb+2zPE005U+Gy5IZl4nOD+vjRC3DYj7ROM3dvxUiq6gnF/ilu24OdAoG8p1gwFiTbBXXuHBhccKKcAXoU7XwtVDOHD5qplJhpnyH3KnrEEf6ZWXF3O8/uJqnB8t0VTraqIZ8/mQv20YyV3qa9uoNinvdPxKHbTRGAXLHF9OOudAYH9uo7M6lLfKYFInlnQm1xyR4Uf2Vt+eh4Uu6Pdc7e+cQj8amV1oBfT1CMiN1oix++YrMnuje0QrlgA0K+NvLd6Lcrag1tTwbXsKVnVXHjZlHhE6ykdMLwEGd6Y5symgxpuVw74pi8zhlaQ9DcCOYM+8mDUj6j8w/sLPv3QNJKy9dmKaZIkizKNEZzOOriTwzjpbWXOKYueb/NT5rPF617aZS5S0CGT3wpAFgOflSbXla1zMszsRKNXhtMZU0vqg3/TIDWlRwmGqOhRZI7kdVdCc6t28h/Foz9qYSBEK/LiZAetOkqHVfRgbiZZKzVaXWohIvAqcEUk08bSMnxpttT+otoc7dWUFvQqS353HVPTOQk4mm0BdlZ71n/aqaJRcQFqxX0iIq29Llk6Vf/de1mZ/rZpJsMLTVw1xDJ3hCML124Rmgeeoh82P7NW/eWvYvFEnp
  template:
    metadata:
      name: regcred
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
