apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgAM8naaXNUNCY41MXKIAdSZC+74LzN0VBpqkC/I3v3OMh+lFVUo04PfEF5d9bRS615u/u3rwPNzU5iccz027zTAzyU6dGErX8tpUZmNVYKalRHuAZ+Mim2kF1400zGEf2+ah0IN16145WsiG5OdhlMpqIBi/OXMrGlqs9+anmOoBJCV4nvzN6gYW3JZbaPIE/VPpvZ612l3ctMqrQI+FGJT6v4AtZwwfp9wBUdWbL2bTMaMLuZqKMBdaegG6pJVECTeuwrvc/papwBCmcdVqHneSO9+vA8BYpqRs3fVPIZu5Vn+uoY8RzYZkRGUcf2qj6ZrKcJerNvRmi0GnwwCNw0OrPnBvXFu7M/xiE6E3X2xT/k5NVe5/3Erv1M39QmRvJG67FBT7FXla86zHWNNYogfsjVUavBMJPLF2Se8Wkqg59XNUHdoLU6t5xVD0uhNxqaVX8BKWx75nsNHr0+qRNHGFT0vEtjz5PjDijfM4Mtb6062FObCEafVajif+bTxSiwmdQ3t8MFpSFApka41L+DikWtE0ClPWOtCcD+Ous5VY6XVD7HpGGJAUN0pu/PVHqk+m/VTLMxW1OPJc6+ABewaPtPgtoB2TIWABjiIlNsSyvSpeH9LJmUXRTGD5Whn79LuF3Nhvhfg7CNPnz7zgabH5jf/TNFnD4KiowHWNLcRRSRxZ/WFIHNnpxW8r/ZqgCbax8yyHFmMAJ53St4TX2ToUZq4nZJ5D4lHVp6hy/AKymi86ULPSmdThyHj73SaXGYOBdCUWrdW0bnS9hsAAuT763iL3FBJbiEEfaMc8haEglmzAHjbT7avvTV5qI8xNn7qVjw9upLMnQ6+xakEw14NYrenGtHtvy5QQMecUl5MkjCQlopUw60PIOMWk7GoJE1JzQswjXJ5pDGrK4eoRfmlzD4DSsCE1flo5Y6xQUYpWHqiQPruV1lX8N+62V5/0hvfUzYt+FdfeuR4
  template:
    metadata:
      name: regcred
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
