---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: questify-postgresql
  namespace: questify
spec:
  encryptedData:
    password: AgAvLy5h+e/5kkXdgQfTtSeJozCZm4hnYFFKT8z3/8jbpGzrs/WPeu32g7b8L2Mjh8SRkFhtUxEEXekhQ/oRig0L8IKJzgvd3luXhDRBoVWsKMQyRulEGUj07IIWWwfMSbKYjhPG68CehQN3Wz8+tNt/LDvVK1a+azfPf6WaBD9LcHS3LZtcLgOt1BGz4iNcLx0oHQCFXKlVuU/aGtQptqAA7S0J4cJRpIh9KkFuFrLmtTsw53Zv4DXgO3Ufuql1zgwKrzYvR9w5JBHHVZuApPVadZ65pVH40xY0B5t9dPiGcXm5ByLoRk/VvM9GhaU01ER8MivkKcqpPAb8JZ6SQ25IJ3wWe8r+vH7s3xBzKTYOplx9D1fgPvxNAbH4KLP1A2hmYw3l6n+fNWW8Wc8rp9aspD3nh+ayFY5VZ0fjWGgjjojCS/W2OJo8zt/15lNU1tW+Buujcon42LCfTwu1LLw99UvYSwVd+sr0CjEucgQ3vtFzCPRk64s+1AuZEubcRt+BZiiM+TsHI937lsOrFLP2RXOZThNupT9dLXJmYZbPZeWQGptZdYgSw+RKPi9LfsEgPrW1OfuvUv+Eu5D9bw4A8lxcR9in+o2i9AJvr8kGcwVS38sf2qOuOex4ok/FtCOokQImWSAWkLPFGs/8+FvBVAp5YaiPRnibk0GEZCSRkaaTvRIWBE58gfAkPVUxlUYSvxSxiaL3JpCaQBE/0JrGY3ietutq/fyD5EwiedTP2DU95SykYlU27eFBaw==
    username: AgCEPqG0/NTlpux/XnXugpw3vqy3B7m76cUSQzw9xMJT4ZHg/XIhQ+KE2SdRZGl8JGYQV2UiLL1LTTW0HS9/dsfzIVj1U0CqwXb39f+p2P33EXFqTuJYAMzjLey+ltMxtbiRJbeekXkhuOAnegFhEU6VYRpmJgu4AK8HTvUB+WPurnhYiXryKvgVgs5OAgOX2+j798+62lppxbktimyGxzON5F2iziTFiMHrmy+KMdP+E2WPq3JxwF2qKSx4Z5TJ23jErgTlMOGOm0qW2cUS9lXprNp6AFvk8cLuAhmZoKiFmw2xEz3BKfV8+5q7/7LSPGDsZZojMDt5aUgTMsyWs+rwUWciYr8Vly9G7CpP18Boulb61HOiNA7GjHCDGJQQ4mvJLh0hXKVaTM7gARofrOyD2Bd4FtmkOChsRex2IiaswdHRw1ZEG9uf73LYRBVhp/SQFyfmFO7kMHJO0ABgmES1P9miLlNjxumSdgSQl3dOSLMPQBpoK5vBlWt2TpvJqm8vqATy/g3RbdrT0jHALCOJ1sbI9XkSifi1OQnmCiBBADPlfC1jIvFnEJBbb2U2teAbVSLWIsqt2bPShu3m32RdK3YWaqx+2avTfsF3I/J1l4rpXdyR+qwHwFE6Hmhy46VPXqLSMtJAsqHOhqUDgbB/bTMldmP0jS2K3Y1L44BzuvyR1KPv3mZ9LqtXg25dMeqj8HHLPP4ATg==
  template:
    metadata:
      name: questify-postgresql
      namespace: questify
