---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: questify-minio
  namespace: questify
spec:
  encryptedData:
    root-password: AgA+qEQUmmjXCnqr2/CfwzwLjWHH5NLLVpAS/1Q+maOmVgHR/0JyQbLX1oxzRvF8VLercIrOsjKENmK5h0NDQvmkZ9PrTn+1RyNBwjWlCw2XMAvtMPC8IseXkaJ1hnQVoEMMyc1SIdEIGWkr0vY+9OsbRxm8GLGAijfEpwaCV6Qjbz86nnZGdhTTrARzb+GuqCWZw1NbN7AvABf2vyqDvEjyrYbAMLhDCSBk8z+1f+6QqLnlWsuESp8VH3pbr1eX/qIQDsDSYrxSoPR+zPDSB7puPJsTUgedgvwQpbpLCSnttjCZnzYhJAxyYl7jnt2XCkYOWUe8m1uj+9QzzsX0ds874DfhkZVdipCY23pUhgPmFjYrcB49WN/bvSgb9pPRi81T5NdMX2nW/u52jrqNNOj7tva7XCIm4HL9fPJpc2mnl1OzJ7a0iACeWml4gjVVFn2pJCdpo9KUxlfE0r3zq1U2t2klJ7X8F8NbzZJ+wfu7KIt6WpCGhuLD9fXTjEA29c+EsV5pumB18RRgbYtSA71bsurrfCHDp7j4Ygd80lmCL5UWKLGo66/DHiGq73KJxyy1WglJ1gylPsqSeV6QuCifGirpwWuPrVCuNy2mOnXgMNTF0lsdE90IbKdw1CGgOO1R7RbLY6hnHgfHfWWZI8gXAbU4738INXK+C75kWzsQqESspu2pA/iopLefK6EN8IxVYJkg0YkzCQtls07zn+fEzz5vw42jUnuh5h43BC+p322B10Ltm6yllDywtQ==
    root-user: AgBLZDVpFMaF52pyi8iU9FM3yCVcP4TY3Ht/C9EbEW0MqpYJLsGBq66hyFpsTEPRAdy2mCioyVbXLecVqynWjkj9VeZa+dfqYbyrNZfc+l1Lt5PY/i16GzBAfI76XyHfCoGlvFqa5qmzHS7TreUBjJMMt4q+3SxUuj/dQb1r4GV2rlbm/CFWPteTNpel7E0J6LUOHrXEYvwNptMsrYoxz/em75C7q4rffFW5rC0nl+XUTrv1t9unydXUkgjHHEICQSj5ADKAuoXvfZUbW3LFiXxIEhkKz7wp+UKkda+y8JD7pDjKfasi/90ED2pYpafL1YLzLl0i7vsbgbw13iCUS2ZdB+6X4gi6ayCrhMIfsKg+gpS9wfVBs28gf9z//SK9tSzKl3NcExSvnvH7ekANMzBvtf+Cwx4PgBj6adc6/wgN8u0JIr/5SfEZAzY8YbZrr4RG/ut6dkFgkbiu47dmvaOST4I2z90URoYJuX1jxn34YunmzFwTHlXpYOdd57BmkOyqewogiMu4/M1ll9y9/U/bPJ8+72Vk2S7bsNweNR3UZH9FvAde6qlaj5ddf7GoBIqu0nUYYsMZSbP1Aa6VcOA6JcF2VTrzwpkKSsEGwZVGIv5xVf9oG6dOyqu2V/OX6RglTnwIIAbDKGP7maHadMpXsIuyl2vSrQkKgjKj6QBc3/hVpWVqnNvXqsz9+gxymUFO2B2L7Q==
  template:
    metadata:
      name: questify-minio
      namespace: questify
