---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: questify
spec:
  encryptedData:
    .dockerconfigjson: AgAKbYo420zZOVR3QPFsdMyk/5cHP0y8O1sgP6/We/saDmGnfbzG/kP3PnYO0i1CMgjyFqq8x76+882pgiYp/msbSw9sff5HeGL9+Tt0kBXTlJRK+gWjMnz5cCgm0uILbtCqSzoH+EYE1CgkgHyuiKH6eV913aF5h5X87bwLqMngMUIMmTMsF5dTLTIyg/zOq6Hn3KP8gWRHUvlWItVA85oNN6yMdljQKhPWHdZEK/ihwOC0qkO/onc0fXxrXHEpDh5DXNr1fNasN7uktHcHTlvkLq6NFqjJ1uuModg+z3Dx3A2AOwaPT7fXFIYxvxrnD5kAgNevFoXJdgmNqbOP5ifiVDUJUeYY0QPCUQqTXuVHpSQ/EdD+z35YBlBHlOIwF5SN7OBYih/C/RCAiMZFiwQzRyHdVosSvz1g7xLvbEz/vWYgMSrU0D6za4K/wRCR3ZCnCBJcBgCGxaTsriF1JdgsHihyp1MWbBLRG9ymcHJkGqiKIkVZK9EeLFmgjm3OGAOuCHJqmcmGhIEQM1veyAuHOJn0x3uJNsnU+t5e02ibtf28LI08dbxOFL713lLdMMZQj+xWFpUbQF1ZttR1lr8OY3URkJ+hgikOCSmCHyEP3uG7CUOBoMIfyZkCv3DzOctCbIdKkT127LOrrT/ld9Kx4x3tVUGLw5D3t55oaUSvE542x+ti5MSMC6vhJ1+HRzACahmtBnIa0/QynEVV9q1T8xQyiz1Zi/z1fiCsF427Bcyr7e/okcwykblTYf4SLhBFc6kVFJAUNYce5O2WZZO1HpQCcZ/kakNI9o6qhIfMkzOlr6JlaWh6/jTDU7aso+9GaiC/LKPxp0aYBOlgG6YVpwtQz8Fo5hAIR3X7WmQEg2w/KlAL82x8O+nVCplXO+Azwxdri4SGb2jMAIMLSLpoAEs6fRy0WxTrjPEZ1nW+KXEzEOiurOboU8Lix/YrfJFVlv2zdcIItGYL
  template:
    metadata:
      name: regcred
      namespace: questify
    type: kubernetes.io/dockerconfigjson
